use porter::sources::umbraco::UmbracoSource;
use porter::targets::payload::PayloadTarget;
use porter::adapter::{SourceReader, TargetWriter, TargetOptions};
use porter::mapping;
use std::fs;
use std::path::Path;
use anyhow::Result;

#[test]
fn test_umbraco_to_payload() -> Result<()> {
    // Setup
    let source = UmbracoSource::new();
    let target = PayloadTarget::new();
    let test_input = vec!["./test-data/hotels.json".to_string()];
    let test_output = "./test-output";
    let collection = "hotels";
    let options = TargetOptions {
        collection: Some(collection.to_string()),
        locale: None,
        related_collections: None,
    };

    // Clean up any previous test output
    if Path::new(test_output).exists() {
        fs::remove_dir_all(test_output)?;
    }

    // Execute
    let docs = source.read_documents(&test_input)?;
    assert!(!docs.is_empty(), "Should have read at least one document");
    
    // Create a mapping
    let mapping = mapping::load_or_create_mapping(
        collection,
        "umbraco",
        "payload",
        &docs,
        None,
        false,
        None
    )?;
    
    // Apply mapping
    let mut transformed_docs = Vec::new();
    for doc in &docs {
        let transformed = mapping::apply_mapping(doc, &mapping)?;
        transformed_docs.push(transformed);
    }
    
    // Write output
    target.emit_seed(&transformed_docs, test_output, &options)?;
    
    // Verify
    let output_path = format!("{}/{}.seed.ts", test_output, collection);
    assert!(Path::new(&output_path).exists(), "Output file should exist");
    
    let content = fs::read_to_string(output_path)?;
    assert!(content.contains("GENERATED BY PORTER"), "Output should contain the generated comment");
    assert!(content.contains("export const seed ="), "Output should export the seed constant");
    
    // Clean up
    fs::remove_dir_all(test_output)?;
    
    Ok(())
}