use porter::sources::umbraco::UmbracoSource;
use porter::targets::payload::PayloadTarget;
use porter::adapter::{SourceReader, TargetWriter, TargetOptions};
use porter::mapping;
use std::fs;
use std::path::Path;
use anyhow::Result;

#[test]
fn test_umbraco_to_payload() -> Result<()> {
    // Setup
    let source = UmbracoSource::new();
    let target = PayloadTarget::new();
    let test_input = vec!["./test-data/hotels.json".to_string()];
    let test_output = "./test-output";
    let collection = "hotels";
    let options = TargetOptions {
        collection: Some(collection.to_string()),
        locale: None,
        related_collections: None,
    };

    // Clean up any previous test output
    if Path::new(test_output).exists() {
        fs::remove_dir_all(test_output)?;
    }

    // Execute
    let docs = source.read_documents(&test_input)?;
    assert!(!docs.is_empty(), "Should have read at least one document");
    
    // Create a mapping
    let mapping = mapping::load_or_create_mapping(
        collection,
        "umbraco",
        "payload",
        &docs,
        None,
        false,
        None
    )?;
    
    // Apply mapping
    let mut transformed_docs = Vec::new();
    for doc in &docs {
        let transformed = mapping::apply_mapping(doc, &mapping)?;
        transformed_docs.push(transformed);
    }
    
    // Write output
    target.emit_seed(&transformed_docs, test_output, &options)?;
    
    // Verify - should create separate files for each document
    let output_dir = Path::new(test_output);
    assert!(output_dir.exists(), "Output directory should exist");
    
    // Check that files were created (should be at least one file per document)
    let entries: Vec<_> = fs::read_dir(output_dir)?.collect::<Result<Vec<_>, _>>()?;
    assert!(!entries.is_empty(), "Should have created at least one seed file");
    
    // Check the first file for proper content
    let first_file = entries[0].path();
    let content = fs::read_to_string(&first_file)?;
    assert!(content.contains("GENERATED BY PORTER"), "Output should contain the generated comment");
    assert!(content.contains("import type { RequiredDataFromCollectionSlug } from 'payload'"), "Output should contain the import statement");
    assert!(content.contains("export const"), "Output should export a function");
    assert!(content.contains("RequiredDataFromCollectionSlug<'"), "Output should contain the type annotation");
    
    // Clean up
    fs::remove_dir_all(test_output)?;
    
    Ok(())
}