// GENERATED BY PORTER
// Collection: hotels

export const seed = [
  {
    "coordinates": {
      "coordinates": [
        25.184771,
        -20.496752
      ],
      "type": "Point"
    },
    "title": "Jack's Camp"
  }
] as const;
